# Generated by Django 4.1.13 on 2026-06-12 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketItemReference',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], max_length=32)),
                ('reference_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_xp', models.FloatField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'market_item_references',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='MarketTypeConfig',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SHOP', 'Shop'), ('CITY_MARKET', 'City market'), ('TEMPORARY_MARKET', 'Temporary market'), ('GUILD_COUNTER', 'Guild counter'), ('PLAYER_MARKET', 'Player market')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('base_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_type_configs',
            },
        ),
        migrations.CreateModel(
            name='MerchantCounter',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SHOP', 'Shop'), ('CITY_MARKET', 'City market'), ('TEMPORARY_MARKET', 'Temporary market'), ('GUILD_COUNTER', 'Guild counter'), ('PLAYER_MARKET', 'Player market')], max_length=32)),
                ('owner_type', models.CharField(choices=[('ADMIN', 'Admin'), ('PLAYER', 'Player'), ('CITY', 'City'), ('GUILD', 'Guild')], max_length=16)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('world', models.CharField(max_length=255)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('sell_mode_enabled', models.BooleanField(default=False)),
                ('buy_mode_enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='markets.city')),
            ],
            options={
                'db_table': 'merchant_counters',
                'ordering': ['name'],
                'unique_together': {('world', 'x', 'y', 'z')},
            },
        ),
        migrations.CreateModel(
            name='PriceCalculationRun',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(max_length=255)),
                ('trigger_source', models.CharField(choices=[('WEBSITE', 'Website'), ('MINECRAFT_COMMAND', 'Minecraft command'), ('SYSTEM', 'System')], max_length=32)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=16)),
                ('calculation_version', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price_calculation_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryMarketModifier',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], max_length=32, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_market_modifiers', to='markets.city')),
            ],
            options={
                'db_table': 'temporary_market_modifiers',
            },
        ),
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('player_uuid', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('ADMIN', 'Admin'), ('PLAYER', 'Player'), ('CITY', 'City'), ('GUILD', 'Guild')], max_length=16)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(max_length=255)),
                ('item_display_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('owner_gain', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_transactions', to='markets.city')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='markets.merchantcounter')),
            ],
            options={
                'db_table': 'market_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantCounterItem',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('buy_enabled', models.BooleanField(default=True)),
                ('sell_enabled', models.BooleanField(default=False)),
                ('auto_price', models.BooleanField(default=True)),
                ('manual_buy_price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('manual_sell_price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_mode', models.CharField(choices=[('UNLIMITED', 'Unlimited'), ('LIMITED', 'Limited'), ('PLAYER_INVENTORY', 'Player inventory')], default='UNLIMITED', max_length=32)),
                ('stock_quantity', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('local_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='markets.merchantcounter')),
            ],
            options={
                'db_table': 'merchant_counter_items',
                'ordering': ['display_name'],
                'unique_together': {('counter', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='CityMarketModifier',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], max_length=32)),
                ('modifier', models.DecimalField(decimal_places=4, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_modifiers', to='markets.city')),
            ],
            options={
                'db_table': 'city_market_modifiers',
                'unique_together': {('city', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CalculatedMarketPrice',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('market_type', models.CharField(choices=[('SHOP', 'Shop'), ('CITY_MARKET', 'City market'), ('TEMPORARY_MARKET', 'Temporary market'), ('GUILD_COUNTER', 'Guild counter'), ('PLAYER_MARKET', 'Player market')], max_length=32)),
                ('item_id', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], max_length=32)),
                ('calculated_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('buy_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sell_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calculation_version', models.CharField(max_length=64)),
                ('calculated_at', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_prices', to='markets.city')),
            ],
            options={
                'db_table': 'calculated_market_prices',
                'unique_together': {('city', 'market_type', 'item_id')},
            },
        ),
    ]
