# Generated by Django 4.1.13 on 2026-06-12 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcounteritem',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='markettypeconfig',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
