# Generated by Django 4.1.13 on 2026-06-12 08:44

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_seed_market_type_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('FOOD', 'Food'), ('WOOD', 'Wood'), ('STONE', 'Stone'), ('IRON', 'Iron'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('FARMING', 'Farming'), ('ALCHEMY', 'Alchemy'), ('LUXURY', 'Luxury'), ('CONSTRUCTION', 'Construction'), ('RARE', 'Rare'), ('GUILD', 'Guild'), ('OTHER', 'Other')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'market_categories',
                'ordering': ['code'],
            },
        ),
    ]
