# Generated by Django 4.1.13 on 2026-06-13 00:00

import django.core.validators
from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_merchantcounter_counter_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketWithdrawal",
            fields=[
                ("id", models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("counter_id", models.CharField(max_length=255)),
                ("owner_uuid", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("amount", models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("withdrawn_at", models.DateTimeField()),
                ("source", models.CharField(choices=[("MINECRAFT", "Minecraft")], default="MINECRAFT", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "market_withdrawals",
                "ordering": ["-withdrawn_at", "-created_at"],
            },
        ),
    ]
