# Generated by Django 4.1.13 on 2026-06-13 00:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0006_marketwithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantcounter",
            name="created_source",
            field=models.CharField(choices=[("MINECRAFT", "Minecraft"), ("WEBSITE", "Website"), ("SYSTEM", "System")], default="MINECRAFT", max_length=32),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="disabled_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="flagged_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="last_owner_interaction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="last_transaction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="moderation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="moderation_status",
            field=models.CharField(choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled"), ("PENDING_REVIEW", "Pending review"), ("FLAGGED", "Flagged")], default="ACTIVE", max_length=32),
        ),
        migrations.AddField(
            model_name="merchantcounter",
            name="risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MarketActivityModifier",
            fields=[
                ("id", models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("item_id", models.CharField(max_length=255)),
                ("category", models.CharField(choices=[("FOOD", "Food"), ("WOOD", "Wood"), ("STONE", "Stone"), ("IRON", "Iron"), ("TOOLS", "Tools"), ("WEAPONS", "Weapons"), ("ARMOR", "Armor"), ("FARMING", "Farming"), ("ALCHEMY", "Alchemy"), ("LUXURY", "Luxury"), ("CONSTRUCTION", "Construction"), ("RARE", "Rare"), ("GUILD", "Guild"), ("OTHER", "Other")], max_length=32)),
                ("buy_quantity", models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("sell_quantity", models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("buy_transaction_count", models.PositiveIntegerField(default=0)),
                ("sell_transaction_count", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("activity_modifier", models.DecimalField(decimal_places=4, default=Decimal("1.0000"), max_digits=8)),
                ("calculation_version", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("city", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activity_modifiers", to="markets.city")),
            ],
            options={
                "db_table": "market_activity_modifiers",
                "ordering": ["-period_end", "item_id"],
            },
        ),
        migrations.CreateModel(
            name="MarketEconomyConfig",
            fields=[
                ("id", models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("dynamic_economy_enabled", models.BooleanField(default=False)),
                ("activity_window_days", models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ("max_activity_modifier_up", models.DecimalField(decimal_places=4, default=Decimal("1.1500"), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("1.0000"))])),
                ("max_activity_modifier_down", models.DecimalField(decimal_places=4, default=Decimal("0.8500"), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0.0100")), django.core.validators.MaxValueValidator(Decimal("1.0000"))])),
                ("min_transactions_for_impact", models.PositiveIntegerField(default=10)),
                ("buy_pressure_weight", models.DecimalField(decimal_places=4, default=Decimal("0.0100"), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("sell_pressure_weight", models.DecimalField(decimal_places=4, default=Decimal("0.0100"), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_economy_config",
            },
        ),
        migrations.CreateModel(
            name="MarketModerationLog",
            fields=[
                ("id", models.CharField(default=markets.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("DISABLED", "Disabled"), ("ENABLED", "Enabled"), ("FLAGGED", "Flagged"), ("STATUS_SYNC", "Status sync")], max_length=32)),
                ("reason", models.TextField(blank=True, null=True)),
                ("performed_by", models.CharField(blank=True, max_length=255, null=True)),
                ("previous_status", models.CharField(blank=True, choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled"), ("PENDING_REVIEW", "Pending review"), ("FLAGGED", "Flagged")], max_length=32, null=True)),
                ("new_status", models.CharField(choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled"), ("PENDING_REVIEW", "Pending review"), ("FLAGGED", "Flagged")], max_length=32)),
                ("counter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="moderation_logs", to="markets.merchantcounter")),
            ],
            options={
                "db_table": "market_moderation_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
