# Generated by Django 3.1.12 on 2025-02-19 14:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('skills', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('mastery', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
