# Generated by Django 4.1.13 on 2025-02-21 13:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("action_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("mana", models.IntegerField()),
                ("chance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("trait_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("bonus", djongo.models.fields.JSONField()),
            ],
        ),
    ]
