# Generated by Django 3.1.12 on 2025-02-19 14:42

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mastery',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
