# Generated by Django 3.1.12 on 2025-02-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20250219_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
