# Generated by Django 4.1.13 on 2025-02-25 16:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_action_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inter_choice',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
