# Generated by Django 5.2 on 2025-04-06 15:31

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_inter_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=334)),
                ('season', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'globals',
            },
        ),
    ]
