# Generated by Django 4.1.13 on 2025-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("en_name", models.CharField(max_length=255)),
                ("fr_name", models.CharField(max_length=255)),
                ("en_description", models.TextField(blank=True)),
                ("fr_description", models.TextField(blank=True)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
