# Generated by Django 4.1.13 on 2025-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="global",
            name="future_modif_add_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="global",
            name="one_session_state",
            field=models.BooleanField(default=False),
        ),
    ]
