from django.urls import path

from . import views


urlpatterns = [
    path("api/markets/dashboard", views.AdminDashboardView.as_view()),
    path("api/markets/recalculate", views.AdminRecalculateView.as_view()),
    path("markets/recalculate/", views.AdminRecalculateView.as_view(), name="market-recalculate"),
    path("api/markets/reference-items", views.AdminReferenceItemListCreateView.as_view()),
    path("api/markets/reference-items/<str:pk>", views.AdminReferenceItemDetailView.as_view()),
    path("api/markets/cities", views.AdminCityListView.as_view()),
    path("api/markets/city-modifiers", views.AdminCityModifierListView.as_view()),
    path("api/markets/city-modifiers/<str:pk>", views.AdminCityModifierDetailView.as_view()),
    path("api/markets/calculated-prices", views.AdminCalculatedPriceListView.as_view()),
    path("api/markets/counters/moderation", views.AdminCounterModerationListView.as_view()),
    path("api/markets/counters", views.AdminCounterListView.as_view()),
    path("api/markets/counters/<str:pk>", views.AdminCounterDetailView.as_view()),
    path("api/markets/counters/<str:pk>/disable", views.AdminCounterDisableView.as_view()),
    path("api/markets/counters/<str:pk>/enable", views.AdminCounterEnableView.as_view()),
    path("api/markets/counters/<str:pk>/flag", views.AdminCounterFlagView.as_view()),
    path("api/markets/counters/<str:pk>/audit", views.AdminCounterAuditView.as_view()),
    path("api/markets/transactions", views.AdminTransactionListView.as_view()),
    path("api/markets/counters/<str:pk>/withdrawals", views.AdminCounterWithdrawalListView.as_view()),
    path("api/markets/withdrawals", views.AdminWithdrawalListView.as_view()),
    path("api/markets/economy/config", views.AdminEconomyConfigView.as_view()),
    path("api/markets/economy/activity", views.AdminEconomyActivityView.as_view()),
    path("api/markets/economy/activity-modifiers", views.AdminEconomyActivityModifierListView.as_view()),
    path("api/markets/economy/recompute-activity", views.AdminEconomyRecomputeActivityView.as_view()),
    path("markets/counters/moderation/", views.AdminCounterModerationListView.as_view(), name="market-counters-moderation"),
    path("markets/counters/<str:pk>/disable/", views.AdminCounterDisableView.as_view(), name="market-counter-disable"),
    path("markets/counters/<str:pk>/enable/", views.AdminCounterEnableView.as_view(), name="market-counter-enable"),
    path("markets/counters/<str:pk>/flag/", views.AdminCounterFlagView.as_view(), name="market-counter-flag"),
    path("markets/counters/<str:pk>/audit/", views.AdminCounterAuditView.as_view(), name="market-counter-audit"),
    path("markets/counters/<str:pk>/withdrawals/", views.AdminCounterWithdrawalListView.as_view(), name="market-counter-withdrawals"),
    path("markets/withdrawals/", views.AdminWithdrawalListView.as_view(), name="market-withdrawals"),
    path("markets/economy/config/", views.AdminEconomyConfigView.as_view(), name="market-economy-config"),
    path("markets/economy/activity/", views.AdminEconomyActivityView.as_view(), name="market-economy-activity"),
    path("markets/economy/activity-modifiers/", views.AdminEconomyActivityModifierListView.as_view(), name="market-economy-activity-modifiers"),
    path("markets/economy/recompute-activity/", views.AdminEconomyRecomputeActivityView.as_view(), name="market-economy-recompute-activity"),
    path("api/markets/calculation-runs", views.AdminCalculationRunListView.as_view()),
    path("minecraft/admin/audit/", views.minecraft_admin_audit, name="minecraft-admin-audit"),
    path("minecraft/markets/prices/current/", views.MinecraftCurrentPricesView.as_view(), name="minecraft-market-prices"),
    path("minecraft/markets/counters/", views.MinecraftCounterListCreateView.as_view(), name="minecraft-market-counters"),
    path("minecraft/markets/counters/<str:counter_id>/", views.MinecraftCounterDetailView.as_view(), name="minecraft-market-counter-detail"),
    path("minecraft/markets/counters/<str:counter_id>/items/", views.MinecraftCounterItemListCreateView.as_view(), name="minecraft-counter-items"),
    path("minecraft/markets/counters/<str:counter_id>/items/<str:item_id>/", views.MinecraftCounterItemDetailView.as_view(), name="minecraft-counter-item-detail"),
    path("minecraft/markets/reference-items/", views.MinecraftReferenceItemListView.as_view(), name="minecraft-reference-items"),
    path("minecraft/jobs/xp-references/", views.MinecraftXpReferenceItemListView.as_view(), name="minecraft-xp-references"),
    path("minecraft/xp/reference-items/", views.MinecraftXpReferenceItemListView.as_view(), name="minecraft-xp-reference-items"),
    path("minecraft/markets/transactions/", views.MinecraftTransactionCreateView.as_view(), name="minecraft-market-transactions"),
    path("minecraft/markets/counters/<str:counter_id>/withdrawals/", views.MinecraftWithdrawalCreateView.as_view(), name="minecraft-counter-withdrawals"),
    path("minecraft/markets/player/<str:player_uuid>/owned-counters/", views.MinecraftOwnedCounterListView.as_view(), name="minecraft-player-owned-counters"),
    path("minecraft/markets/counters/<str:counter_id>/transactions/", views.MinecraftCounterTransactionListView.as_view(), name="minecraft-counter-transactions"),
    path("api/public/market-prices", views.PublicMarketPricesView.as_view()),
    path("markets/public-prices/", views.PublicMarketPricesView.as_view(), name="market-public-prices"),
]
