# Generated by Django 4.1.13 on 2025-06-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0002_player_real_charact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "season",
                    models.IntegerField(
                        choices=[
                            (1, "Printemps"),
                            (2, "Été"),
                            (3, "Automne"),
                            (4, "Hiver"),
                        ]
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Joueurs participant à cette session",
                        related_name="sessions",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SessionFuture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restrictions",
                    models.JSONField(
                        default=list,
                        help_text="Liste de dicts {metier: str, level: int}",
                    ),
                ),
                ("cost", models.IntegerField(help_text="Coût en points / ressources")),
                (
                    "description",
                    models.TextField(help_text="Énoncé de la proposition future"),
                ),
                (
                    "reward",
                    models.CharField(help_text="Récompense prévue", max_length=255),
                ),
                ("question", models.TextField(help_text="Question à poser au joueur")),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="Réponse du joueur (sera remplie ultérieurement)",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Joueur ayant proposé ce futur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_futures",
                        to="players.player",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session à laquelle cette proposition appartient",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futures",
                        to="game_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
