# Generated by Django 4.1.13 on 2025-06-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_real_charact"),
        ("game_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SessionFuture",
            new_name="Future",
        ),
    ]
