# Generated by Django 4.1.13 on 2025-06-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_real_charact"),
        ("game_sessions", "0002_rename_sessionfuture_future"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-created_date"]},
        ),
        migrations.RenameField(
            model_name="session",
            old_name="date",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="session",
            name="session_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de la session programmée",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SessionMoney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "money",
                    models.FloatField(
                        help_text="Solde du joueur au moment de la session"
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_money_snapshots",
                        to="players.player",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_snapshots",
                        to="game_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "unique_together": {("session", "player")},
            },
        ),
        migrations.AddField(
            model_name="session",
            name="players_money",
            field=models.ManyToManyField(
                blank=True,
                help_text="Snapshots de solde des joueurs",
                related_name="sessions_with_money",
                through="game_sessions.SessionMoney",
                to="players.player",
            ),
        ),
    ]
