# Generated by Django 4.1.13 on 2025-06-20 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_real_charact'),
        ('game_sessions', '0003_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='chance',
            field=models.FloatField(default=1.0, help_text='Probabilité en pourcentage (0.0–1.0)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='future',
            name='type',
            field=models.CharField(choices=[('exploration', 'Exploration'), ('construction', 'Construction'), ('caisse_royale', 'La caisse royale !'), ('rejoindre_armee', 'Rejoindre l’armée'), ('tenir_magasin', 'Tenir le magasin'), ('travailler', 'Travailler'), ('espionner', 'Espionner'), ('sentrainer', 'S’entraîner')], default='Exploration', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='future',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='future',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='future',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='future',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clé primaire unique (UUID) générée automatiquement', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='future',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_futures', to='players.player'),
        ),
        migrations.AlterField(
            model_name='future',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='future',
            name='restrictions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='future',
            name='reward',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='future',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures', to='game_sessions.session'),
        ),
    ]
