# Generated by Django 4.1.13 on 2026-02-19 13:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('category', models.CharField(choices=[('Main', 'Main'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('FullRP', 'FullRP'), ('SemiRP', 'SemiRP')], max_length=50)),
                ('questId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parentId', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('prerequisitesAll', djongo.models.fields.JSONField(blank=True, default=list)),
                ('prerequisitesAny', djongo.models.fields.JSONField(blank=True, default=list)),
                ('npc', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Solo', 'Solo'), ('Multi', 'Multi'), ('Hybrid', 'Hybrid')], default='Solo', max_length=50)),
                ('description', djongo.models.fields.JSONField(default=dict)),
                ('objectives', djongo.models.fields.JSONField(default=list)),
                ('xp', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('money', models.IntegerField(default=0)),
                ('rewards', djongo.models.fields.JSONField(blank=True, default=list)),
                ('beginText', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('endText', djongo.models.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'quests',
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestState',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=255)),
                ('quest_id', models.CharField(max_length=255)),
                ('members', djongo.models.fields.JSONField(default=list)),
                ('status', models.CharField(choices=[('LOCKED', 'LOCKED'), ('AVAILABLE', 'AVAILABLE'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='LOCKED', max_length=50)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_quest_states',
                'unique_together': {('player_id', 'quest_id')},
            },
        ),
    ]
