# -*- coding: utf-8 -*-
import json
from jobs.models import Trait, Action

traits_data = {
    1: {"trait_id": 1, "Name": "Etudiant", "Bonus": {"skill": 2, "rethoric": 2}},
    2: {"trait_id": 2, "Name": "Iwwyn", "Bonus": {"mana": 20, "charisma": 1}},
    3: {"trait_id": 3, "Name": "Garde", "Bonus": {"resistance": 1, "strength": 1}},
    4: {"trait_id": 4, "Name": "Sang bleu", "Bonus": {"influence": 1, "life": 2}},
    5: {"trait_id": 5, "Name": "Cuisinier", "Bonus": {"life": 1, "regeneration": 1}},
    6: {"trait_id": 6, "Name": "Travailleur", "Bonus": {"skill": 2, "strength": 1}},
    7: {"trait_id": 7, "Name": "Voleur", "Bonus": {"speed": 1, "influence": -1, "discretion": 2}},
    8: {"trait_id": 8, "Name": "Vagabon", "Bonus": {"speed": 1, "dodge": 1}},
    9: {"trait_id": 9, "Name": "Lâche", "Bonus": {"reputation": -3, "charisma": -1}},
    10: {"trait_id": 10, "Name": "Guilde des créatures", "Bonus": {"life": 1, "skill": 4}},
    11: {"trait_id": 11, "Name": "Extravertie", "Bonus": {"charisma": 1, "influence": 1}},
    12: {"trait_id": 12, "Name": "Guilde maritime", "Bonus": {"mana": 20, "skill": 2}},
    13: {"trait_id": 13, "Name": "Fermier", "Bonus": {"resistance": 1, "regeneration": 1}},
    14: {"trait_id": 14, "Name": "Alcoolique", "Bonus": {"life": 1, "influence": -1}},
    15: {"trait_id": 15, "Name": "AutoEntrepreneur", "Bonus": {"skill": 2, "influence": 1, "reputation": 4}},
    16: {"trait_id": 16, "Name": "Tolard", "Bonus": {"strength": 1, "resistance": 1}},
    17: {"trait_id": 17, "Name": "Aspirante", "Bonus": {"mana": 10}},
    18: {"trait_id": 18, "Name": "Diligent", "Bonus": {"skill": 2, "speed": 2, "discretion": -2}},
    19: {"trait_id": 19, "Name": "Brûlure",             "Bonus": {"charisma": -1, "resistance": 1}},
    20: {"trait_id": 20, "Name": "Guilde des mineurs",  "Bonus": {"resistance": 1, "skill": 4}},
    21: {"trait_id": 21, "Name": "Mauvais",             "Bonus": {"skill": -2}},
    22: {"trait_id": 22, "Name": "Arnaqueur",           "Bonus": {"negotiation": 1, "rethoric": 1}},
    23: {"trait_id": 23, "Name": "Commandant",          "Bonus": {"strength": 2, "charisma": 2}},
    24: {"trait_id": 24, "Name": "Mercenaire",          "Bonus": {"strength": 2}},
    25: {"trait_id": 25, "Name": "Garde Royale",        "Bonus": {"resistance": 2, "strength": 1}},
    26: {"trait_id": 26, "Name": "Charmeur",            "Bonus": {"charisma": 2, "influence": 1, "discretion": -1}},
    27: {"trait_id": 27, "Name": "Déprimé",             "Bonus": {"life": -1}},
    28: {"trait_id": 28, "Name": "Bléssé",              "Bonus": {"life": -1}},
    29: {"trait_id": 29, "Name": "Endurcie",            "Bonus": {"resistance": 1}},
    30: {"trait_id": 30, "Name": "Lêche botte",         "Bonus": {"reputation": -3, "charisma": 1}},
    31: {"trait_id": 31, "Name": "Guilde de la table",  "Bonus": {"regeneration": 1, "skill": 4}},
}

actions_data = {
  "1":  { "action_id": 1,  "Name": "Étude des créatures",                       "Description": "Analyser en détail une créature pour en connaître les faiblesses.",                              "Mana": 0,   "Chance": 100 },
  "2":  { "action_id": 2,  "Name": "Contrôle mental de créature",            "Description": "Prendre brièvement le contrôle de l’esprit d’une créature.",                                        "Mana": 60,  "Chance": 75  },
  "3":  { "action_id": 3,  "Name": "Arnaquer une cible",                       "Description": "Manipuler habilement une personne pour en tirer un bénéfice.",                                        "Mana": 0,   "Chance": 80  },
  "4":  { "action_id": 4,  "Name": "Embobiner quelqu’un",                     "Description": "Convaincre quelqu’un par la ruse et le discours.",                                                   "Mana": 0,   "Chance": 85  },
  "5":  { "action_id": 5,  "Name": "Plaidoirie insistante",                   "Description": "Se plaindre avec force pour exiger un changement immédiat.",                                         "Mana": 0,   "Chance": 90  },
  "6":  { "action_id": 6,  "Name": "Développement industriel",                "Description": "Mettre en place ou améliorer une industrie pour accroître le commerce.",                             "Mana": 0,   "Chance": 75  },
  "7":  { "action_id": 7,  "Name": "Discussion technique",                    "Description": "Aborder des sujets pointus et partager un savoir spécialisé.",                                       "Mana": 0,   "Chance": 95  },
  "8":  { "action_id": 8,  "Name": "Enchantement de mobilier",               "Description": "Imprégner un meuble de magie pour lui conférer des propriétés spéciales.",                           "Mana": 110, "Chance": 25  },
  "9":  { "action_id": 9,  "Name": "Provocation au duel",                     "Description": "Défier formellement un adversaire en duel.",                                                         "Mana": 0,   "Chance": 50  },
  "10": { "action_id": 10, "Name": "Imposition de respect",                   "Description": "Affirmer son autorité pour se faire respecter.",                                                     "Mana": 0,   "Chance": 85  },
  "11": { "action_id": 11, "Name": "Renforcement d’objet",                    "Description": "Améliorer la durabilité d’un objet grâce à un sortilège.",                                          "Mana": 80,  "Chance": 35  },
  "12": { "action_id": 12, "Name": "Lévitation d’objets",                     "Description": "Utiliser la magie pour faire flotter plusieurs objets.",                                       "Mana": 20,  "Chance": 90  },
  "13": { "action_id": 13, "Name": "Performance vocale",                      "Description": "Donner une prestation chantée avec maîtrise et puissance.",                                          "Mana": 0,   "Chance": 85  },
  "14": { "action_id": 14, "Name": "Enchantement du bois",                    "Description": "Imbiber un objet en bois de magie afin de le renforcer.",                                            "Mana": 75,  "Chance": 60  },
  "15": { "action_id": 15, "Name": "Charme ciblé",                            "Description": "Séduire et influencer subtilement une personne.",                                                     "Mana": 110, "Chance": 75  },
  "16": { "action_id": 16, "Name": "Manipulation de l’esprit",                "Description": "Altérer la perception d’une personne ou d’une créature.",                                           "Mana": 35,  "Chance": 35  },
  "17": { "action_id": 17, "Name": "Protection magique",                      "Description": "Créer un champ magique pour protéger un bâtiment.",                                                   "Mana": 100, "Chance": 10  },
  "18": { "action_id": 18, "Name": "Invocation du monde miroir",              "Description": "Appeler une entité issue du monde miroir.",                                                         "Mana": 180, "Chance": 5   },
  "19": { "action_id": 19, "Name": "Connaissances culinaires",                "Description": "Maîtriser l’art de la cuisine pour préparer des plats exceptionnels.",                               "Mana": 0,   "Chance": 100 },
  "20": { "action_id": 20, "Name": "Danse de scène",                          "Description": "Exécuter une danse professionnelle devant un public.",                                                "Mana": 0,   "Chance": 90  },
  "21": { "action_id": 21, "Name": "Festivités royales",                     "Description": "Organiser et animer une fête grandiose.",                                                           "Mana": 0,   "Chance": 95  },
  "22": { "action_id": 22, "Name": "Maîtrise de l’eau",                       "Description": "Contrôler de puissants jets d’eau par magie.",                                                        "Mana": 100, "Chance": 50  },
  "23": { "action_id": 23, "Name": "Démonstration de force",                  "Description": "Faire étalage de sa puissance physique pour impressionner.",                                         "Mana": 0,   "Chance": 80  },
  "24": { "action_id": 24, "Name": "Enchantement de pierre",                  "Description": "Imprégner un caillou de magie pour lui conférer des capacités spéciales.",                           "Mana": 110, "Chance": 25  },
  "25": { "action_id": 25, "Name": "Enchantement de nourriture",              "Description": "Transformer des aliments en mets magiques.",                                                        "Mana": 75,  "Chance": 60  },
  "26": { "action_id": 26, "Name": "Virtuosité instrumentale",               "Description": "Jouer d’un instrument avec un talent remarquable.",                                                  "Mana": 0,   "Chance": 85  },
  "27": { "action_id": 27, "Name": "Étude approfondie des créatures",         "Description": "Approfondir ses connaissances sur les caractéristiques d’une créature.",                            "Mana": 0,   "Chance": 100 },
  "28": { "action_id": 28, "Name": "Manipulation mentale avancée",            "Description": "Contrôler finement une créature pour la forcer à obéir.",                                           "Mana": 60,  "Chance": 75  },
  "29": { "action_id": 29, "Name": "Arnaque experte",                          "Description": "Monter une escroquerie élaborée pour maximiser le gain.",                                           "Mana": 0,   "Chance": 100 },
  "30": { "action_id": 30, "Name": "Tromperie raffinée",                      "Description": "Embrocher une personne dans un mensonge subtile.",                                                  "Mana": 0,   "Chance": 100 },
  "31": { "action_id": 31, "Name": "Plaintes organisées",                     "Description": "Coordonner une action de protestation pour obtenir des réformes.",                                   "Mana": 0,   "Chance": 100 },
  "32": { "action_id": 32, "Name": "Expansion industrielle",                  "Description": "Étendre une entreprise en fournissant de nouveaux services.",                                       "Mana": 0,   "Chance": 100 },
  "33": { "action_id": 33, "Name": "Table ronde technique",                   "Description": "Animer un débat spécialisé entre experts.",                                                        "Mana": 0,   "Chance": 100 },
  "34": { "action_id": 34, "Name": "Envoûtement de meuble",                   "Description": "Accorder des pouvoirs magiques à un meuble pour qu’il réagisse aux commandes.",                    "Mana": 110, "Chance": 25  },
  "35": { "action_id": 35, "Name": "Défi formel au duel",                     "Description": "Émettre un défi officiel à un adversaire pour un duel honorifique.",                                "Mana": 0,   "Chance": 100 },
  "36": { "action_id": 36, "Name": "Autorité imposée",                         "Description": "Réclamer et obtenir le respect par une présence dominante.",                                        "Mana": 0,   "Chance": 100 },
  "37": { "action_id": 37, "Name": "Solidification d’objet",                  "Description": "Renforcer magiquement un objet pour le rendre quasi indestructible.",                              "Mana": 80,  "Chance": 35  },
  "38": { "action_id": 38, "Name": "Distorsion mentale",                      "Description": "Modifier la réalité perçue par l’esprit d’une cible.",                                             "Mana": 35,  "Chance": 35  },
  "39": { "action_id": 39, "Name": "Barrière protectrice",                    "Description": "Eriger un bouclier magique autour d’une construction.",                                             "Mana": 100, "Chance": 10  },
  "40": { "action_id": 40, "Name": "Télékinésie avancée",                     "Description": "Faire voler plusieurs objets simultanément avec précision.",                                       "Mana": 20,  "Chance": 90  },
  "41": { "action_id": 41, "Name": "Invocation miroir majeure",                "Description": "Faire apparaître une entité puissante du monde miroir.",                                           "Mana": 180, "Chance": 5   },
  "42": { "action_id": 42, "Name": "Expertise culinaire",                     "Description": "Préparer des mets délicats dignes des plus grands chefs.",                                          "Mana": 0,   "Chance": 100 },
  "43": { "action_id": 43, "Name": "Danse professionnelle",                   "Description": "Réaliser une chorégraphie élaborée devant un auditoire.",                                          "Mana": 0,   "Chance": 100 },
  "44": { "action_id": 44, "Name": "Chant virtuose",                          "Description": "Interpréter une pièce vocale avec une justesse exceptionnelle.",                                   "Mana": 0,   "Chance": 100 },
  "45": { "action_id": 45, "Name": "Enchantement sylvestre",                  "Description": "Incorporer la magie de la nature dans un objet en bois.",                                          "Mana": 75,  "Chance": 60  },
  "46": { "action_id": 46, "Name": "Séduction ciblée",                        "Description": "Charmer une cible spécifique pour obtenir son soutien.",                                           "Mana": 110, "Chance": 75  },
  "47": { "action_id": 47, "Name": "Injure cinglante",                        "Description": "Lancer une insulte suffisamment aiguë pour déstabiliser.",                                        "Mana": 0,   "Chance": 100 },
  "48": { "action_id": 48, "Name": "Organisation de festin",                  "Description": "Planifier un grand banquet pour réunir des convives distingués.",                                  "Mana": 0,   "Chance": 95  },
  "49": { "action_id": 49, "Name": "Domination aquatique",                     "Description": "Maîtriser le flux de l’eau pour submerger ou protéger.",                                           "Mana": 100, "Chance": 50  },
  "50": { "action_id": 50, "Name": "Démonstration de force ultime",            "Description": "Exécuter un exploit physique hors du commun.",                                                     "Mana": 0,   "Chance": 80  },
  "51": { "action_id": 51, "Name": "Enchantement de caillou",                  "Description": "Imprégner un petit galet de magie concentrée.",                                                   "Mana": 110, "Chance": 25  },
  "52": { "action_id": 52, "Name": "Élan courageux",                           "Description": "Invoquer un surcroît de bravoure pour soi ou un allié.",                                           "Mana": 0,   "Chance": 100 },
  "53": { "action_id": 53, "Name": "Nourriture enchantée",                     "Description": "Rendre des provisions magiques aux effets variés.",                                                "Mana": 75,  "Chance": 60  },
  "54": { "action_id": 54, "Name": "Concert instrumental",                     "Description": "Donner un récital instrumental éblouissant.",                                                    "Mana": 0,   "Chance": 100 },
  "55": { "action_id": 55, "Name": "Argumentation persuasive",                 "Description": "Convaincre un auditoire grâce à une argumentation implacable.",                                   "Mana": 0,   "Chance": 100 },
  "56": { "action_id": 56, "Name": "Cri retentissant",                        "Description": "Pousser un hurlement puissant pour désorienter l’ennemi.",                                       "Mana": 0,   "Chance": 100 },
  "57": { "action_id": 57, "Name": "Enchantement de vêtement",                 "Description": "Insuffler un sort protecteur ou utilitaire à un habit.",                                          "Mana": 100, "Chance": 50  },
  "58": { "action_id": 58, "Name": "S’illustrer en public",                   "Description": "Se faire remarquer par un acte spectaculaire.",                                                  "Mana": 0,   "Chance": 100 },
  "59": { "action_id": 59, "Name": "Gestion administrative",                   "Description": "Traiter efficacement la paperasse et les formalités.",                                           "Mana": 0,   "Chance": 100 },
  "60": { "action_id": 60, "Name": "Demande de rénovation",                   "Description": "Soumettre une requête officielle pour rénover un bâtiment.",                                     "Mana": 0,   "Chance": 100 },
  "61": { "action_id": 61, "Name": "Demande de prêt bancaire",               "Description": "Faire une demande formelle de prêt auprès d’une institution.",                                    "Mana": 0,   "Chance": 100 },
  "62": { "action_id": 62, "Name": "Recrutement d’apprenti",                  "Description": "Proposer un apprentissage au sein de la guilde ou de l’entreprise.",                              "Mana": 0,   "Chance": 100 },
  "63": { "action_id": 63, "Name": "Fabrication d’artefacts magiques",        "Description": "Concevoir et créer des objets imprégnés de puissances mystiques.",                               "Mana": 0,   "Chance": 100 },
  "64": { "action_id": 64, "Name": "Inscription à l’hôtel de vente animalier","Description": "Rejoindre le marché spécialisé des créatures rares.",                                            "Mana": 0,   "Chance": 100 },
  "65": { "action_id": 65, "Name": "Emprunt à la Banque du Sang Jaune",       "Description": "Obtenir des fonds auprès de la Banque du Sang Jaune.",                                          "Mana": 0,   "Chance": 100 },
  "66": { "action_id": 66, "Name": "Organisation d’un festin",                "Description": "Mettre sur pied un grand repas pour marquer un événement.",                                      "Mana": 0,   "Chance": 100 },
  "67": { "action_id": 67, "Name": "Concours de pêche",                       "Description": "Organiser une compétition de pêche ouverte à tous.",                                             "Mana": 0,   "Chance": 100 },
  "68": { "action_id": 68, "Name": "Commande auprès de la guilde",            "Description": "Passer une commande officielle de ravitaillement.",                                             "Mana": 0,   "Chance": 100 },
  "69": { "action_id": 69, "Name": "Détournement de fonds",                   "Description": "Rediriger illégalement les ressources financières d’une organisation.",                        "Mana": 0,   "Chance": 100 },
  "70": { "action_id": 70, "Name": "Réforme des règles de guilde",            "Description": "Proposer et faire adopter de nouvelles règles internes.",                                         "Mana": 0,   "Chance": 100 },
  "71": { "action_id": 71, "Name": "Attribution de rôle",                     "Description": "Nommer un membre à une fonction spécifique au sein de la guilde.",                               "Mana": 0,   "Chance": 100 },
  "72": { "action_id": 72, "Name": "Audience royale",                         "Description": "Rencontrer des représentants de la cour pour négocier ou conseiller.",                           "Mana": 0,   "Chance": 100 },
  "73": { "action_id": 73, "Name": "Augmentation des contributions",          "Description": "Faire voter une hausse des apports financiers des membres.",                                     "Mana": 0,   "Chance": 100 },
  "74": { "action_id": 74, "Name": "Gestion des subventions",                 "Description": "Allouer des fonds publics ou privés à des projets spécifiques.",                                   "Mana": 0,   "Chance": 100 },
  "75": { "action_id": 75, "Name": "Conseil à la couronne",                   "Description": "Fournir des recommandations stratégiques au souverain.",                                         "Mana": 0,   "Chance": 100 },
  "76": { "action_id": 76, "Name": "Rapport à la guilde",                     "Description": "Faire un compte-rendu officiel des activités et résultats.",                                      "Mana": 0,   "Chance": 100 },
  "77": { "action_id": 77, "Name": "Administration villageoise",              "Description": "Gérer les membres et ressources d’un village affilié.",                                          "Mana": 0,   "Chance": 100 },
  "78": { "action_id": 78, "Name": "Fermeture d’établissement",              "Description": "Ordonner la fermeture temporaire ou définitive d’un lieu.",                                       "Mana": 0,   "Chance": 100 },
  "79": { "action_id": 79, "Name": "Inspection réglementaire",                "Description": "Vérifier la conformité des pratiques aux règlements en vigueur.",                                  "Mana": 0,   "Chance": 100 },
  "80": { "action_id": 80, "Name": "Recrutement collectif",                   "Description": "Organiser le recrutement de plusieurs travailleurs via la guilde.",                               "Mana": 0,   "Chance": 100 },
  "81": { "action_id": 81, "Name": "Paiement des cotisations",                 "Description": "Collecter ou verser les contributions annuelles des membres.",                                    "Mana": 0,   "Chance": 100 },
  "82": { "action_id": 82, "Name": "Demande de subvention",                   "Description": "Solliciter un financement public ou privé pour un projet.",                                       "Mana": 0,   "Chance": 100 },
  "83": { "action_id": 83, "Name": "Organisation de manifestation",           "Description": "Lancer et coordonner un rassemblement public pour une cause.",                                   "Mana": 0,   "Chance": 100 },
  "84": { "action_id": 84, "Name": "Création de faction politique",           "Description": "Fonder un groupe politique pour défendre des intérêts communs.",                                  "Mana": 0,   "Chance": 100 },
  "85": { "action_id": 85, "Name": "Réforme successorale",                    "Description": "Proposer un nouveau système d’héritage dans la société.",                                         "Mana": 0,   "Chance": 100 },
  "86": { "action_id": 86, "Name": "Changement de régime politique",          "Description": "Mettre en place une nouvelle forme de gouvernement.",                                             "Mana": 0,   "Chance": 100 },
  "87": { "action_id": 87, "Name": "Révolte contre le royaume",                "Description": "Organiser une insurrection pour renverser le pouvoir en place.",                                  "Mana": 0,   "Chance": 100 },
  "88": { "action_id": 88, "Name": "Candidature à la Banque Jaune",           "Description": "Soumettre son profil pour rejoindre la Banque du Sang Jaune.",                                   "Mana": 0,   "Chance": 100 },
  "89": { "action_id": 89, "Name": "Entretien à la Banque Jaune",             "Description": "Rencontrer un représentant de la Banque du Sang Jaune pour discuter d’affaires.",                  "Mana": 0,   "Chance": 100 },
  "90": { "action_id": 90, "Name": "Organisation d’événement",                "Description": "Planifier et coordonner une manifestation ou une foire.",                                        "Mana": 0,   "Chance": 100 },
  "91": { "action_id": 91, "Name": "Concert public",                         "Description": "Monter un concert ouvert à la population.",                                                       "Mana": 0,   "Chance": 100 }
}


for trait in traits_data.values():
    Trait.objects.get_or_create(trait_id=trait["trait_id"], name=trait["Name"], bonus=trait["Bonus"])

for action in actions_data.values():
    Action.objects.get_or_create(
        action_id=action["action_id"],
        name=action["Name"],
        description=action["Description"],
        mana=action["Mana"],
        chance=action["Chance"]
    )

print("✅ Données initiales insérées avec succès !")