# Generated by Django 4.1.13 on 2026-02-20 11:43

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('npc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DECO', 'DECO'), ('SHOPKEEPER', 'SHOPKEEPER'), ('QUEST', 'QUEST')], default='DECO', max_length=50)),
                ('skin', models.CharField(blank=True, max_length=255, null=True)),
                ('dialogue', djongo.models.fields.JSONField(blank=True, default=list)),
                ('tags', djongo.models.fields.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idle_behavior', models.CharField(blank=True, max_length=50, null=True)),
                ('ambient_lines', djongo.models.fields.JSONField(blank=True, default=list)),
                ('shop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('open_message', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_category', models.CharField(blank=True, max_length=255, null=True)),
                ('quest_giver', models.BooleanField(default=False)),
                ('quest_validator', models.BooleanField(default=False)),
                ('quest_ids', djongo.models.fields.JSONField(blank=True, default=list)),
                ('dialogue_by_state', djongo.models.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'npcs',
            },
        ),
        migrations.CreateModel(
            name='NpcSpawn',
            fields=[
                ('spawn_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('world', models.CharField(default='world', max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('yaw', models.FloatField(default=0.0)),
                ('pitch', models.FloatField(default=0.0)),
                ('spawn_rule', models.CharField(choices=[('STATIC', 'STATIC'), ('TIMER', 'TIMER'), ('ROAD', 'ROAD'), ('ADMIN', 'ADMIN')], default='STATIC', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('meta', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='npcs.npc')),
            ],
            options={
                'db_table': 'npc_spawns',
            },
        ),
    ]
