# Generated by Django 4.1.13 on 2026-03-06 10:54

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='met_by',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='npc',
            name='profile_image',
            field=models.CharField(default='NPCdefault.png', max_length=255),
        ),
    ]
