# Generated by Django 4.1.13 on 2026-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0002_npc_description_npc_met_by_npc_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='region',
            field=models.CharField(default='Royaume de Renblood', max_length=255),
        ),
    ]
