# Generated by Django 3.1.12 on 2025-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_minecraft', models.CharField(max_length=255, unique=True)),
                ('pseudo_minecraft', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('total_lvl', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.CharField(default='Citoyen', max_length=255)),
                ('money', models.FloatField(default=0.0)),
                ('divin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
