# Generated by Django 3.1.12 on 2025-02-20 13:26

from django.db import migrations, models
import djongo.models.fields
import players.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_minecraft', models.CharField(max_length=255, unique=True)),
                ('pseudo_minecraft', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.CharField(default='Citoyen', max_length=255)),
                ('money', models.FloatField(default=0.0)),
                ('divin', models.BooleanField(default=False)),
                ('life', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=100)),
                ('reach', models.IntegerField(default=5)),
                ('resistance', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=18)),
                ('haste', models.IntegerField(default=78)),
                ('regeneration', models.IntegerField(default=1)),
                ('trait', djongo.models.fields.JSONField(default=list)),
                ('actions', djongo.models.fields.JSONField(default=list)),
                ('dodge', models.IntegerField(default=2)),
                ('discretion', models.IntegerField(default=3)),
                ('charisma', models.IntegerField(default=1)),
                ('rethoric', models.IntegerField(default=1)),
                ('mana', models.IntegerField(default=100)),
                ('negotiation', models.IntegerField(default=0)),
                ('influence', models.IntegerField(default=1)),
                ('skill', models.IntegerField(default=100)),
                ('experiences', djongo.models.fields.JSONField(default=players.models.default_jobs_experience)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
