# Generated by Django 5.1.6 on 2025-02-19 13:26

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("id_minecraft", models.CharField(max_length=255, unique=True)),
                ("pseudo_minecraft", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("rank", models.CharField(default="Citoyen", max_length=255)),
                ("money", models.FloatField(default=0.0)),
                ("divin", models.BooleanField(default=False)),
                ("trait", djongo.models.fields.JSONField(default=list)),
                ("actions", djongo.models.fields.JSONField(default=list)),
                ("experiences", djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                "db_table": "players",
            },
        ),
    ]
