# Generated by Django 4.1.13 on 2025-06-17 08:01

from django.db import migrations
import djongo.models.fields
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="real_charact",
            field=djongo.models.fields.JSONField(
                blank=True,
                default=players.models.default_real_charact,
                help_text="JSON des bonus réels, ex. {'life': {'count':5,'type':'TalentTree'}}",
                validators=[players.models.validate_real_charact],
            ),
        ),
    ]
