# Generated by Django 4.1.13 on 2025-02-20 09:04

from django.db import migrations, models
import djongo.models.fields
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='charisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='discretion',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='dodge',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='haste',
            field=models.IntegerField(default=78),
        ),
        migrations.AddField(
            model_name='player',
            name='influence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='life',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='negotiation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='place',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='player',
            name='reach',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='regeneration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rethoric',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='experiences',
            field=djongo.models.fields.JSONField(default=players.models.default_jobs_experience),
        ),
    ]
