# Generated by Django 4.1.13 on 2025-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_real_charact"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="discord_avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="discord_discriminator",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="discord_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="discord_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
