# Generated by Django 4.1.13 on 2025-08-18 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_player_discord_avatar_player_discord_discriminator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="patreon",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
