# Generated by Django 4.1.13 on 2026-01-22 11:18

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_patreon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('exploitant_name', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='players.player')),
            ],
            options={
                'db_table': 'licences',
            },
        ),
    ]
